
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//Component
import Layout from "@/components/Layout";

//Redux
import ReduxPersist from "@/store/storeProvide"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxPersist>
      <html className="flex flex-col h-full w-full " lang="en">
        <body className={`${inter.className} h-full w-ful `}>
          <Layout>{children}</Layout>
        </body>
      </html>
    </ReduxPersist>
  );
}
